# Generated by Django 3.0.5 on 2020-04-14 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_delivery', models.BooleanField(blank=True, default=False, null=True)),
                ('total_money', models.FloatField(blank=True, null=True)),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Bill',
                'db_table': 'tb_bill',
            },
        ),
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Bill Detail',
                'db_table': 'tb_bill_detail',
            },
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=245)),
                ('password', models.CharField(max_length=12)),
                ('phone', models.DecimalField(decimal_places=10, max_digits=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Consumers',
                'db_table': 'tb_consumer',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True)),
                ('id_bill_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.BillDetail')),
            ],
            options={
                'verbose_name': 'Goods',
                'db_table': 'tb_goods',
            },
        ),
        migrations.AddField(
            model_name='billdetail',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.Consumer'),
        ),
    ]
