# Generated by Django 3.0.5 on 2020-04-16 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='is_delete',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='consumer',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='consumer',
            old_name='is_delete',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='consumer',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='consumer',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='StaffPerformBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.Bill')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Perform Bill',
                'db_table': 'tb_staff_perform_bill',
            },
        ),
    ]
